/*
 * generated by Xtext
 */
package com.github.evra.jcr.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.github.evra.jcr.ui.internal.CndActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CndExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CndActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CndActivator.getInstance().getInjector(CndActivator.COM_GITHUB_EVRA_JCR_CND);
	}
	
}
