/*
* generated by Xtext
*/
package com.github.evra.jcr;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CndUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.github.evra.jcr.ui.internal.CndActivator.getInstance().getInjector("com.github.evra.jcr.Cnd");
	}
	
}
