/*
* generated by Xtext
*/
package com.github.evra.jcr.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.github.evra.jcr.services.CndGrammarAccess;

public class CndParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CndGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.github.evra.jcr.parser.antlr.internal.InternalCndParser createParser(XtextTokenStream stream) {
		return new com.github.evra.jcr.parser.antlr.internal.InternalCndParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public CndGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CndGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
