<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cnd" nsURI="http://www.github.com/evra/jcr/Cnd" nsPrefix="cnd">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespaces" upperBound="-1"
        eType="#//NsMapping" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeTypes" upperBound="-1"
        eType="#//NodeTypeDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeTypeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredSupertypeNames"
        unique="false" upperBound="-1" eType="#//NodeTypeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mixin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notqueryable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryItem" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredPropertyDefinitions"
        upperBound="-1" eType="#//PropertyDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="declaredChildNodeDefinitions"
        upperBound="-1" eType="#//NodeDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredTypes" unique="false"
        upperBound="-1" eType="#//NodeTypeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultType" eType="#//NodeTypeDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autocreated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manadatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onParentVersion" eType="#//Opv"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sameNameSiblings" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValues" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autocreated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onParentVersion" eType="#//Opv"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="queryOps" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noFullText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noQueryOrder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueConstraints" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Opv">
    <eLiterals name="COPY" literal="COPY"/>
    <eLiterals name="VERSION" value="1" literal="VERSION"/>
    <eLiterals name="INITIALIZE" value="2" literal="INITIALIZE"/>
    <eLiterals name="COMPUTE" value="3" literal="COMPUTE"/>
    <eLiterals name="IGNORE" value="4" literal="IGNORE"/>
    <eLiterals name="ABORT" value="5" literal="ABORT"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyType">
    <eLiterals name="UNDEFINED" literal="UNDEFINED"/>
    <eLiterals name="TSTRING" value="1" literal="STRING"/>
    <eLiterals name="TBINARY" value="2" literal="BINARY"/>
    <eLiterals name="TLONG" value="3" literal="LONG"/>
    <eLiterals name="TDOUBLE" value="4" literal="DOUBLE"/>
    <eLiterals name="DDATE" value="5" literal="DATE"/>
    <eLiterals name="TBOOLEAN" value="6" literal="BOOLEAN"/>
    <eLiterals name="TNAME" value="7" literal="NAME"/>
    <eLiterals name="TPATH" value="8" literal="PATH"/>
    <eLiterals name="TREFERENCE" value="9" literal="REFERENCE"/>
    <eLiterals name="TWEAKREFERENCE" value="10" literal="WEAKREFERENCE"/>
    <eLiterals name="TURI" value="11" literal="URI"/>
    <eLiterals name="TDECIMAL" value="12" literal="DECIMAL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NsMapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
