/*
 * generated by Xtext
 */
package com.evrasoft.jcr.ui.contentassist

import com.evrasoft.jcr.ui.contentassist.AbstractCndProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CndProposalProvider extends AbstractCndProposalProvider {
}
