/*
* generated by Xtext
*/
package com.github.evra.jcr;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CndStandaloneSetup extends CndStandaloneSetupGenerated{

	public static void doSetup() {
		new CndStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

