/**
 * generated by Xtext
 */
package com.github.evra.jcr.validation;

import com.github.evra.jcr.validation.AbstractCndValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CndValidator extends AbstractCndValidator {
  public final static String MISSING_NODETYPEDEF = "com.github.evra.jcr.missing.nodetypedef";
}
