/*
 * generated by Xtext
 */
package com.github.evra.jcr.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCndValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.github.evra.jcr.cnd.CndPackage.eINSTANCE);
		return result;
	}
}
